// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package weighttracker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WeightTrackerClient is the client API for WeightTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeightTrackerClient interface {
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
}

type weightTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightTrackerClient(cc grpc.ClientConnInterface) WeightTrackerClient {
	return &weightTrackerClient{cc}
}

func (c *weightTrackerClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, "/WeightTracker/AddRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightTrackerServer is the server API for WeightTracker service.
// All implementations must embed UnimplementedWeightTrackerServer
// for forward compatibility
type WeightTrackerServer interface {
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	mustEmbedUnimplementedWeightTrackerServer()
}

// UnimplementedWeightTrackerServer must be embedded to have forward compatible implementations.
type UnimplementedWeightTrackerServer struct {
}

func (UnimplementedWeightTrackerServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedWeightTrackerServer) mustEmbedUnimplementedWeightTrackerServer() {}

// UnsafeWeightTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightTrackerServer will
// result in compilation errors.
type UnsafeWeightTrackerServer interface {
	mustEmbedUnimplementedWeightTrackerServer()
}

func RegisterWeightTrackerServer(s grpc.ServiceRegistrar, srv WeightTrackerServer) {
	s.RegisterService(&_WeightTracker_serviceDesc, srv)
}

func _WeightTracker_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightTrackerServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WeightTracker/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightTrackerServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeightTracker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WeightTracker",
	HandlerType: (*WeightTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _WeightTracker_AddRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weighttracker/weight_tracker.proto",
}
